In [1]:
import re
import os
import numpy as np

In [2]:
def preprocess_string(str_arg):
    
    """"
        ---------
        Preprocessed string     
    """
    cleaned_str=str_arg.strip("\n")
    cleaned_str=re.sub('[^a-z\s]+',' ',str_arg,flags=re.IGNORECASE) #every char except alphabets is replaced
    #cleaned_str=re.sub('(\s+)',' ',cleaned_str) #multiple spaces are replaced by single space
    cleaned_str=cleaned_str.lower() #converting the cleaned string to lower case
    
    return cleaned_str # eturning the preprocessed string in tokenized form

In [3]:
def convertFileToCharacters(filename) :   
    f = open(filename, 'r')
    content = f.readlines()
    file_characters = []
    for lines in content :
        preprocessed = preprocess_string(lines)
        if preprocessed != ' ':
            file_characters.extend(list(preprocessed))
    return file_characters

In [4]:
def BOW(document):
    count = {}
    bowVector = np.zeros((27,1))
    for letters in document:
        if letters in count:
            count[letters] += 1
        else:
            count[letters] = 1
    #print (sorted(count.keys()))
    for i in range(26):
        if chr(ord('a')+i) in count.keys():
            bowVector[i] = count[chr(ord('a')+i)]
    bowVector[26] = count[' ']
    return bowVector


In [5]:
## define P(c|y=e)


def classConditionalProb (classname):
    count_giv_class = np.zeros((27,1))
    for filename in os.listdir("languageID"):
        if filename.endswith(".txt") and filename.startswith(classname):
            if int (filename.strip(".txt").strip(classname)) <= 9:
                count_giv_class += BOW(convertFileToCharacters("languageID/"+filename))
                
    return count_giv_class


In [6]:
classConditionalProb("e")

array([[ 910.],
       [ 168.],
       [ 325.],
       [ 332.],
       [1594.],
       [ 286.],
       [ 264.],
       [ 714.],
       [ 838.],
       [  21.],
       [  56.],
       [ 438.],
       [ 310.],
       [ 876.],
       [ 975.],
       [ 253.],
       [   8.],
       [ 814.],
       [1001.],
       [1212.],
       [ 403.],
       [ 140.],
       [ 234.],
       [  17.],
       [ 209.],
       [   9.],
       [2712.]])

In [7]:
np.ones((27,1))+classConditionalProb("e")

array([[ 911.],
       [ 169.],
       [ 326.],
       [ 333.],
       [1595.],
       [ 287.],
       [ 265.],
       [ 715.],
       [ 839.],
       [  22.],
       [  57.],
       [ 439.],
       [ 311.],
       [ 877.],
       [ 976.],
       [ 254.],
       [   9.],
       [ 815.],
       [1002.],
       [1213.],
       [ 404.],
       [ 141.],
       [ 235.],
       [  18.],
       [ 210.],
       [  10.],
       [2713.]])

In [8]:
#q3.2
Qe = (np.ones((27,1))+classConditionalProb("e"))/ (sum (classConditionalProb("e")) + 27)
Qe

array([[0.06014789],
       [0.01115806],
       [0.02152383],
       [0.021986  ],
       [0.10530833],
       [0.0189489 ],
       [0.01749637],
       [0.04720718],
       [0.05539416],
       [0.00145253],
       [0.00376337],
       [0.02898455],
       [0.02053347],
       [0.05790308],
       [0.06443946],
       [0.0167701 ],
       [0.00059422],
       [0.05380959],
       [0.06615608],
       [0.08008715],
       [0.02667371],
       [0.00930939],
       [0.01551565],
       [0.00118843],
       [0.01386505],
       [0.00066024],
       [0.1791232 ]])

In [30]:
np.set_printoptions(precision=None, suppress=True)

In [31]:
#q3.3
Qj = (np.ones((27,1))+classConditionalProb("j"))/ (sum (classConditionalProb("j")) + 27)

In [32]:
Qj

array([[0.13167632],
       [0.01089157],
       [0.0055156 ],
       [0.01724499],
       [0.06018292],
       [0.0039098 ],
       [0.01403337],
       [0.03176709],
       [0.09697689],
       [0.0023738 ],
       [0.05739021],
       [0.00146617],
       [0.03979613],
       [0.05669203],
       [0.0911122 ],
       [0.00090763],
       [0.00013964],
       [0.0427983 ],
       [0.04216994],
       [0.0569713 ],
       [0.07058577],
       [0.00027927],
       [0.01975843],
       [0.00006982],
       [0.01417301],
       [0.00774977],
       [0.12336801]])

In [35]:
#q3.3
Qs = (np.ones((27,1))+classConditionalProb("s"))/ (sum (classConditionalProb("s")) + 27)

In [36]:
Qs

array([[0.10450428],
       [0.00825682],
       [0.03752542],
       [0.03974367],
       [0.113747  ],
       [0.00862653],
       [0.00720932],
       [0.00455974],
       [0.04984904],
       [0.00665475],
       [0.00030809],
       [0.05292994],
       [0.02581798],
       [0.0541623 ],
       [0.07246288],
       [0.02427753],
       [0.00770226],
       [0.0592766 ],
       [0.0657465 ],
       [0.03561526],
       [0.0337051 ],
       [0.00591534],
       [0.00012324],
       [0.00252634],
       [0.00788712],
       [0.0027112 ],
       [0.16815577]])

In [13]:
#q4

In [38]:
x = BOW(convertFileToCharacters("languageID/"+"e10.txt"))
x

array([[164.],
       [ 32.],
       [ 53.],
       [ 57.],
       [311.],
       [ 55.],
       [ 51.],
       [140.],
       [140.],
       [  3.],
       [  6.],
       [ 85.],
       [ 64.],
       [139.],
       [182.],
       [ 53.],
       [  3.],
       [141.],
       [186.],
       [225.],
       [ 65.],
       [ 31.],
       [ 47.],
       [  4.],
       [ 38.],
       [  2.],
       [498.]])

In [40]:
#q5 Expected probability
log_p_x_ye = float(sum(np.multiply(x,np.log10(Qe))))
log_p_x_ye 

-3405.644556038407

In [41]:
log_p_x_yj = float(sum(np.multiply(x,np.log10(Qj))))
log_p_x_yj 

-3804.210716450759

In [42]:
log_p_x_ys = float(sum(np.multiply(x,np.log10(Qs))))
log_p_x_ys 

-3670.8233803708918

In [18]:
#q6 Posterior probability
log_p_ye_x = log_p_x_ye + np.log10(11/33)
log_p_ye_x

-3406.1216772931266

In [19]:
log_p_yj_x = log_p_x_yj + np.log10(11/33)
log_p_yj_x

-3804.6878377054786

In [20]:
log_p_ys_x = log_p_x_ys + np.log10(11/33)
log_p_ys_x

-3671.3005016256116

In [21]:
10**log_p_ye_x/(10**log_p_ye_x + 10**log_p_yj_x + 10**log_p_ys_x)

/u/a/b/abhayk/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """Entry point for launching an IPython kernel.


nan

In [22]:
def predict (classname):
    count_giv_class = np.zeros((27,1))
    classified_as_english = 0
    classified_as_Japanese = 0
    classified_as_spanish = 0

    for filename in os.listdir("languageID"):
        if filename.endswith(".txt") and filename.startswith(classname):
            if int (filename.strip(".txt").strip(classname)) > 9:
                x = BOW(convertFileToCharacters("languageID/"+filename))
                log_p_ye_x = float(sum(np.multiply(x,np.log(Qe)))) + np.log(11/33)
                log_p_yj_x = float(sum(np.multiply(x,np.log(Qj)))) + np.log(11/33)
                log_p_ys_x = float(sum(np.multiply(x,np.log(Qs)))) + np.log(11/33)
                if  log_p_ye_x == max (log_p_ye_x, log_p_yj_x, log_p_ys_x) : 
                    class_predicted = 'e'
                    classified_as_english += 1
                elif log_p_yj_x == max (log_p_ye_x, log_p_yj_x, log_p_ys_x) : 
                    class_predicted = 'j'
                    classified_as_Japanese += 1
                else: 
                    class_predicted = 's'
                    classified_as_spanish += 1
    return classified_as_english, classified_as_Japanese, classified_as_spanish

In [23]:
predict('e')

(10, 0, 0)

In [24]:
predict('j')

(0, 10, 0)

In [25]:
predict('s')

(0, 0, 10)

In [26]:
np.array([-7834.31435832]) == max(np.array([-8444.41505703]), np.array([-8743.75335553]), np.array([-7834.31435832]))

array([ True])

In [27]:
float(np.array([-7834.31435832]) )

-7834.31435832

In [28]:
#WEKA FILE CREATION
for filename in os.listdir("languageID_Weka"):
    x = convertFileToCharacters("languageID_Weka/"+filename)
    fout = open(filename[0] +"/"+"weka_"+filename, "w")
    print ("FILENAME########################" + filename)
    for character in x:
        if character == ' ':
            character = 'space'
        fout.write(character+ ' ' )
    fout.close()

FileNotFoundError: [Errno 2] No such file or directory: 's/weka_s15.txt'

In [ ]:

filename.startswith("e")

In [ ]:
filename = 'e10.txt'
filename[0]

In [ ]:
x = ['o', 'u', 'r', ' ', 's', 'u', 'n', ' ', 'i', 's', ' ', 'i', 'n', ' ', 'a', ' ', 'm', 'o', 'r', 'e', ' ', 'o', 'r', ' ', 'l', 'e', 's', 's', ' ', 'c', 'e', 'n', 't', 'r', 'a', 'l', ' ', 'r', 'e', 'g', 'i', 'o', 'n', ' ', 'o', 'f', ' ', 't', 'h', 'e', ' ', 'u', 'n', 'i', 'v', 'e', 'r', 's', 'e', ' ', 'o', 'r', ' ', 'a', ' ', 'f', 'e', 'w', ' ', 'h', 'u', 'n', 'd', 'r', 'e', 'd', ' ', 't', 'r', 'i', 'l', 'l', 'i', 'o', 'n', ' ', 'm', 'i', 'l', 'e', 's', ' ', 'f', 'r', 'o', 'm', ' ', 't', 'h', 'e', ' ', 'a', 'c', 't', 'u', 'a', 'l', ' ', 'c', 'e', 'n', 't', 'r', 'e', ' ', 't', 'h', 'e', ' ', 'r', 'e', 'm', 'a', 'i', 'n', 'd', 'e', 'r', ' ', 'o', 'f', ' ', 't', 'h', 'e', ' ', 's', 't', 'a', 'r', 's', ' ', 'w', 'h', 'i', 'c', 'h', ' ', 'a', 'r', 'e', ' ', 'a', 'l', 'l', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' ', 'o', 'u', 'r', ' ', 's', 'o', 'l', 'a', 'r', ' ', 's', 'y', 's', 't', 'e', 'm', ' ', 'a', 'r', 'e', ' ', 's', 'p', 'r', 'e', 'a', 'd', ' ', 'o', 'u', 't', ' ', 'a', 'p', 'p', 'a', 'r', 'e', 'n', 't', 'l', 'y', ' ', 'i', 'n', ' ', 'a', 'n', ' ', 'e', 'n', 'o', 'r', 'm', 'o', 'u', 's', ' ', 'd', 'i', 's', 'c', 'l', 'i', 'k', 'e', ' ', 'c', 'o', 'l', 'l', 'e', 'c', 't', 'i', 'o', 'n', ' ', 's', 'o', ' ', 'v', 'a', 's', 't', ' ', 't', 'h', 'a', 't', ' ', 'e', 'v', 'e', 'n', ' ', 'a', ' ', 'r', 'a', 'y', ' ', 'o', 'f', ' ', 'l', 'i', 'g', 'h', 't', ' ', 'w', 'h', 'i', 'c', 'h', ' ', 't', 'r', 'a', 'v', 'e', 'l', 's', ' ', 'a', 't', ' ', 't', 'h', 'e', ' ', 'r', 'a', 't', 'e', ' ', 'o', 'f', ' ', 'm', 'i', 'l', 'e', 's', ' ', 'a', ' ', 's', 'e', 'c', 'o', 'n', 'd', ' ', 'w', 'o', 'u', 'l', 'd', ' ', 't', 'a', 'k', 'e', ' ', 'y', 'e', 'a', 'r', 's', ' ', 't', 'o', ' ', 't', 'r', 'a', 'v', 'e', 'l', ' ', 'f', 'r', 'o', 'm', ' ', 'o', 'n', 'e', ' ', 'e', 'n', 'd', ' ', 'o', 'f', ' ', 'i', 't', ' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 'o', 't', 'h', 'e', 'r', ' ', 't', 'h', 'i', 's', ' ', 't', 'h', 'e', 'n', ' ', 'i', 's', ' ', 'w', 'h', 'a', 't', ' ', 'w', 'e', ' ', 'c', 'a', 'l', 'l', ' ', 'o', 'u', 'r', ' ', 'u', 'n', 'i', 'v', 'e', 'r', 's', 'e', ' ', 't', 'h', 'e', ' ', 'a', 's', 't', 'r', 'o', 'n', 'o', 'm', 'e', 'r', ' ', 'h', 'a', 's', ' ', 'd', 'i', 'v', 'i', 'd', 'e', 'd', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 'i', 'n', 't', 'o', ' ', 'd', 'e', 'f', 'i', 'n', 'i', 't', 'e', ' ', 'c', 'o', 'n', 'c', 'e', 'n', 't', 'r', 'i', 'c', ' ', 'r', 'e', 'g', 'i', 'o', 'n', 's', ' ', 'o', 'r', ' ', 'l', 'a', 'y', 'e', 'r', 's', ' ', 't', 'h', 'e', 's', 'e', ' ', 'l', 'a', 'y', 'e', 'r', 's', ' ', 'e', 'n', 'v', 'e', 'l', 'o', 'p', ' ', 't', 'h', 'e', ' ', 'n', 'u', 'c', 'l', 'e', 'u', 's', ' ', 'o', 'r', ' ', 'c', 'e', 'n', 't', 'r', 'a', 'l', ' ', 'b', 'o', 'd', 'y', ' ', 'o', 'f', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 's', 'o', 'm', 'e', 'w', 'h', 'a', 't', ' ', 'a', 's', ' ', 't', 'h', 'e', ' ', 'a', 't', 'm', 'o', 's', 'p', 'h', 'e', 'r', 'e', ' ', 'e', 'n', 'v', 'e', 'l', 'o', 'p', 's', ' ', 'o', 'u', 'r', ' ', 'e', 'a', 'r', 't', 'h', ' ', 'i', 't', ' ', 'i', 's', ' ', 't', 'h', 'r', 'o', 'u', 'g', 'h', ' ', 't', 'h', 'e', 's', 'e', ' ', 'v', 'a', 'p', 'o', 'u', 'r', ' ', 'l', 'a', 'y', 'e', 'r', 's', ' ', 't', 'h', 'a', 't', ' ', 't', 'h', 'e', ' ', 'b', 'r', 'i', 'g', 'h', 't', ' ', 'w', 'h', 'i', 't', 'e', ' ', 'b', 'o', 'd', 'y', ' ', 'o', 'f', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 'i', 's', ' ', 's', 'e', 'e', 'n', ' ', 'o', 'f', ' ', 't', 'h', 'e', ' ', 'i', 'n', 'n', 'e', 'r', 'm', 'o', 's', 't', ' ', 'r', 'e', 'g', 'i', 'o', 'n', ' ', 't', 'h', 'e', ' ', 'h', 'e', 'a', 'r', 't', ' ', 'o', 'r', ' ', 'n', 'u', 'c', 'l', 'e', 'u', 's', ' ', 'o', 'f', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 'w', 'e', ' ', 'k', 'n', 'o', 'w', ' ', 'a', 'l', 'm', 'o', 's', 't', ' ', 'n', 'o', 't', 'h', 'i', 'n', 'g', ' ', 't', 'h', 'e', ' ', 'c', 'e', 'n', 't', 'r', 'a', 'l', ' ', 'b', 'o', 'd', 'y', ' ', 'o', 'r', ' ', 'n', 'u', 'c', 'l', 'e', 'u', 's', ' ', 'i', 's', ' ', 's', 'u', 'r', 'r', 'o', 'u', 'n', 'd', 'e', 'd', ' ', 'b', 'y', ' ', 'a', ' ', 'b', 'r', 'i', 'l', 'l', 'i', 'a', 'n', 't', 'l', 'y', ' ', 'l', 'u', 'm', 'i', 'n', 'o', 'u', 's', ' ', 'e', 'n', 'v', 'e', 'l', 'o', 'p', 'e', ' ', 'o', 'r', ' ', 'l', 'a', 'y', 'e', 'r', ' ', 'o', 'f', ' ', 'v', 'a', 'p', 'o', 'r', 'o', 'u', 's', ' ', 'm', 'a', 't', 't', 'e', 'r', ' ', 'w', 'h', 'i', 'c', 'h', ' ', 'i', 's', ' ', 'w', 'h', 'a', 't', ' ', 'w', 'e', ' ', 's', 'e', 'e', ' ', 'w', 'h', 'e', 'n', ' ', 'w', 'e', ' ', 'l', 'o', 'o', 'k', ' ', 'a', 't', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 'a', 'n', 'd', ' ', 'w', 'h', 'i', 'c', 'h', ' ', 't', 'h', 'e', ' ', 'a', 's', 't', 'r', 'o', 'n', 'o', 'm', 'e', 'r', ' ', 'c', 'a', 'l', 'l', 's', ' ', 't', 'h', 'e', ' ', 'p', 'h', 'o', 't', 'o', 's', 'p', 'h', 'e', 'r', 'e', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 'w', 'h', 'a', 't', ' ', 'i', 's', ' ', 'i', 't', 's', ' ', 'c', 'o', 'm', 'p', 'o', 's', 'i', 't', 'i', 'o', 'n', ' ', 'w', 'e', ' ', 'k', 'n', 'o', 'w', ' ', 't', 'h', 'a', 't', ' ', 't', 'h', 'e', 'r', 'e', ' ', 'a', 'r', 'e', ' ', 'p', 'r', 'e', 's', 'e', 'n', 't', ' ', 'i', 'n', ' ', 'a', ' ', 'g', 'a', 's', 'e', 'o', 'u', 's', ' ', 's', 't', 'a', 't', 'e', ' ', 's', 'u', 'c', 'h', ' ', 'w', 'e', 'l', 'l', 'k', 'n', 'o', 'w', 'n', ' ', 'e', 'l', 'e', 'm', 'e', 'n', 't', 's', ' ', 'a', 's', ' ', 's', 'o', 'd', 'i', 'u', 'm', ' ', 'i', 'r', 'o', 'n', ' ', 'c', 'o', 'p', 'p', 'e', 'r', ' ', 'z', 'i', 'n', 'c', ' ', 'a', 'n', 'd', ' ', 'm', 'a', 'g', 'n', 'e', 's', 'i', 'u', 'm', ' ', 'i', 'n', 'd', 'e', 'e', 'd', ' ', 'w', 'e', ' ', 'k', 'n', 'o', 'w', ' ', 't', 'h', 'a', 't', ' ', 't', 'h', 'e', 'r', 'e', ' ', 'i', 's', ' ', 'p', 'r', 'a', 'c', 't', 'i', 'c', 'a', 'l', 'l', 'y', ' ', 'e', 'v', 'e', 'r', 'y', ' ', 'e', 'l', 'e', 'm', 'e', 'n', 't', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 't', 'h', 'a', 't', ' ', 'w', 'e', ' ', 'k', 'n', 'o', 'w', ' ', 't', 'o', ' ', 'b', 'e', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 'e', 'a', 'r', 't', 'h', ' ', 'h', 'o', 'w', ' ', 'd', 'o', ' ', 'w', 'e', ' ', 'k', 'n', 'o', 'w', ' ', 'i', 's', ' ', 't', 'h', 'e', ' ', 's', 'u', 'n', ' ', 'd', 'y', 'i', 'n', 'g', ' ', 'f', 'i', 'g', ' ', 't', 'h', 'e', ' ', 'm', 'o', 'o', 'n', ' ', 'f', 'i', 'g', ' ', 'c', 'o', 'm', 'e', 't', ' ', 's', 'e', 'p', 't', 'e', 'm', 'b', 'e', 'r', ' ']

In [ ]:
for character in x:
    if character == ' ':
        character = 'space'
    print(character+ ' ' )